# -*- coding: utf-8 -*-
"""ML_LAB-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v4tv-rEnZ9e0YywHSd-lkOZg3WwqlpES

https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/datasets/data/boston_house_prices.csv

 **Download** boston_house_price.csv
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# %matplotlib inline

boston = pd.read_csv("boston_house_prices.csv")
boston.keys()

boston.head()

boston.isnull().sum()

sns.set(rc={'figure.figsize':(11.7,8.27)})

#bins take min and make and break it in to bins value 1-200 tak 5 5 ki bin bana ligi
#displot ma line nhi hoti yah histrogram show kar nay kliya hai

sns.displot(boston['MEDV'], bins=20)
plt.show()

sns.set(rc={'figure.figsize':(11.7,8.27)})

#bins take min and make and break it in to bins value 1-200 tak 5 5 ki bin bana ligi
sns.distplot(boston['MEDV'], bins=30)
plt.show()

sns.set(rc={'figure.figsize':(11.7,8.27)})

#bins take min and make and break it in to bins value 1-200 tak 5 5 ki bin bana ligi
sns.histplot(boston['MEDV'], bins=20)
plt.show()

correlation_matrix = boston.corr().round(2)
#heatmap is use to identy correlation
sns.heatmap(data=correlation_matrix, annot=True)

plt.figure(figsize=(20,5))

features = ['LSTAT', 'RM']
target = boston['MEDV']

for i,col in enumerate(features):
  plt.subplot(1, len(features), i+1)
  x = boston[col]
  y = target
  plt.scatter(x,y, marker='o')
  plt.title(col)
  plt.xlabel(col)
  plt.ylabel('MEDV')

X = pd.DataFrame(np.c_[boston['LSTAT'], boston['RM']], columns=['LSTAT','RM'])
Y = boston['MEDV']

