# -*- coding: utf-8 -*-
"""ML-Lecture-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGjYwZbJFJsbKNIfHkSIYh-5dghtqms8

# ***Numpy***
The Basics
"""

import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([[4, 5, 6], [7, 8, 9]])
print(b)

a.ndim  #number dimensional array
b.ndim  #number dimensional array

a.shape

a.dtype

a.itemsize

a.size

"""**Accessing/Channing sep. ele, rows clo.**"""

a = np.array([[1,2,3,4,5,6,7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

a.shape

print(a[1,-2])

print(a[0, :])

a[:, 2]

a[0, 1:-1:2]

a[1, 5] = 20
print(a)
a[:,2] = [1,2]
print(a)

np.zeros((2, 3))

np.ones((4,3), dtype = 'int32')

np.full((2, 2), 4, dtype='float32')

np.full_like(a.shape, 4)

np.random.rand(4,2)

np.random.randint(4, size=(4,2))

np.identity(5)

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

out = np.ones((5, 5))
print(out)
z = np.zeros((3, 3))
z[1,1] = 9
print(z)
out[1:-1, 1:-1] = z
print(out)



